# Generated by Django 3.2 on 2021-04-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imc', '0002_alter_usuarios_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='imc',
            field=models.FloatField(default=0.0),
        ),
    ]
