# Generated by Django 3.2 on 2021-04-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imc', '0004_auto_20210419_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='altura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='imc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='peso',
            field=models.FloatField(),
        ),
    ]
