# Generated by Django 3.2 on 2021-04-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imc', '0005_auto_20210419_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='imc',
            field=models.FloatField(default=0.0),
        ),
    ]
